version: '3'

services:
  mysql:
    build:
      context: ../
      dockerfile: docker/Dockerfile.database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./../database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
