version: '3'

services:
  mysql:
    build:
      context: ../
      dockerfile: docker/Dockerfile.database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./../database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - .env
    networks:
      - app-network

  server:
    depends_on:
      - mysql
    image: ghcr.io/parinovyt/technicalsupportcenterproject:latest
    restart: always
    env_file:
      - .env
    ports:
      - "80:8080"
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - app-network

networks:
 app-network:
   driver: bridge

volumes:
  mysql_data: