name: CI-CD

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update
        run: sudo apt-get update
      
      - name: Run MySql Server
        run: make docker-deploy
      
      - name: Init venv and requirements
        run: make init
      
      - name: Run Tests
        run: make test

  mirror-to-gitlab:
    name: Mirror to GitLab
    needs: tests
    runs-on: ubuntu-latest
    if: ${{ needs.tests.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Updating
        run: |
          sudo apt-get update
      
      - name: Mirror to GitLab
        run: |
          git remote add gitlab ${{secrets.GITLABURL}}
          git fetch --unshallow
          git push --quiet gitlab --mirror || true
